# Generated by Django 4.2.27 on 2026-01-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField()),
                ('des1', models.TextField()),
            ],
            options={
                'verbose_name': 'Add About des',
            },
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(upload_to='uploads/')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Add Category',
            },
        ),
        migrations.CreateModel(
            name='mealChallenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='orange', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OwnRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipe', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ParentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ptitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuickRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('ingrident', models.TextField()),
                ('quick_recipe', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('quick_img', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Add Quick recipe',
            },
        ),
        migrations.CreateModel(
            name='Sitereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.TextField(max_length=15)),
                ('des', models.TextField()),
                ('Rating', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=255, unique=True)),
                ('session_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'All users profile',
            },
        ),
        migrations.CreateModel(
            name='ParentSubCatTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentSTitle', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('Stitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='base_app.parenttitle')),
            ],
        ),
        migrations.CreateModel(
            name='ParentRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecipeName', models.CharField(max_length=200)),
                ('parent_image', models.ImageField(upload_to='uploads/')),
                ('Parent_ing', models.TextField()),
                ('Parent_steps', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('Rtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='base_app.parentsubcattitle')),
            ],
        ),
        migrations.CreateModel(
            name='MenuRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('Item_price', models.IntegerField()),
                ('menu_recipe', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('Menu_img', models.ImageField(upload_to='uploads/')),
                ('Menu_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='base_app.itemlist')),
            ],
            options={
                'verbose_name': 'Add Menu recipe',
            },
        ),
        migrations.CreateModel(
            name='mealtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='base_app.mealchallenges')),
            ],
        ),
        migrations.CreateModel(
            name='mealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='base_app.mealtitles')),
            ],
        ),
    ]
