# Generated by Django 4.2.27 on 2026-02-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_mealtitles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': '📌About → AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '📚BookPage → Books'},
        ),
        migrations.AlterModelOptions(
            name='itemlist',
            options={'verbose_name_plural': '📂Menu → Categories'},
        ),
        migrations.AlterModelOptions(
            name='mealchallenges',
            options={'verbose_name_plural': '🍲MealPage → title'},
        ),
        migrations.AlterModelOptions(
            name='mealrecipe',
            options={'verbose_name_plural': '🍲MealPage → Recipes'},
        ),
        migrations.AlterModelOptions(
            name='mealtitles',
            options={'verbose_name_plural': '🍲MealPage → Stitles'},
        ),
        migrations.AlterModelOptions(
            name='menurecipe',
            options={'verbose_name_plural': '🍽️MenuPage → Recipes'},
        ),
        migrations.AlterModelOptions(
            name='ownrecipe',
            options={'verbose_name_plural': '👨\u200d🍳Users → Recipes'},
        ),
        migrations.AlterModelOptions(
            name='parentrecipe',
            options={'verbose_name_plural': '🧩ParentPage → Recipes'},
        ),
        migrations.AlterModelOptions(
            name='parentsubcattitle',
            options={'verbose_name_plural': '🧩ParentPage →Stitles'},
        ),
        migrations.AlterModelOptions(
            name='parenttitle',
            options={'verbose_name_plural': '🧩ParentPage → Titles'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '👤Users → Profiles'},
        ),
        migrations.AlterModelOptions(
            name='quickrecipe',
            options={'verbose_name_plural': '⚡QuickPage → Recipes'},
        ),
        migrations.AlterModelOptions(
            name='sitereview',
            options={'verbose_name_plural': '⭐Users Reviews'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name_plural': '👁️ Site Visitors'},
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
