# Generated by Django 4.2.27 on 2026-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_aboutus_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
