# Generated by Django 4.2.27 on 2026-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_plancategory_plan_ourplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancategory',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
