# Generated by Django 4.2.27 on 2026-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_plancategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
