# Generated by Django 4.2.27 on 2026-03-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_plancategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moody_Name', models.CharField(max_length=40)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': '📂Mood → Categories',
            },
        ),
        migrations.CreateModel(
            name='MoodyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('Item_price', models.IntegerField()),
                ('moody_recipe', models.TextField()),
                ('moody_ingrident', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('Menu_img', models.ImageField(upload_to='uploads/')),
                ('Menu_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood', to='base_app.itemlist')),
            ],
            options={
                'verbose_name_plural': '🍽️MenuPage → Recipes',
            },
        ),
    ]
