# Generated by Django 4.2.27 on 2026-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_moodlist_moodyrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodyrecipe',
            options={'verbose_name_plural': '🍽️MoodyPage → Recipes'},
        ),
        migrations.RenameField(
            model_name='moodyrecipe',
            old_name='Menu_Cat',
            new_name='Mood_Cat',
        ),
        migrations.RemoveField(
            model_name='moodyrecipe',
            name='Item_price',
        ),
    ]
