# Generated by Django 4.2.27 on 2026-03-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_moodyrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodyrecipe',
            name='Mood_Cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood', to='base_app.moodlist'),
        ),
    ]
