# Generated by Django 4.2.27 on 2026-03-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_cart_order_alter_moodlist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Site Dashboard',
                'verbose_name_plural': '📊 Site Dashboard',
            },
        ),
    ]
