# Generated by Django 4.2.27 on 2026-03-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': ' Site Dashboard', 'verbose_name_plural': ' Site Dashboard'},
        ),
    ]
