# Generated by Django 4.2.27 on 2026-03-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0014_alter_dashboard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_type', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card')], max_length=10)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '👑 Premium Users',
            },
        ),
    ]
