"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xb%mhd916(=dbqwto#c6&c1=^)u1xie9@zaygcm68z$!pv#&9z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.ngrok-free.app',
    '.ngrok-free.dev',
]


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base_app',
    'rangefilter', 
    # 'base_app.apps.BaseAppConfig',
]
JAZZMIN_SETTINGS = {
    "site_title": "SpiceFit Admin",
    "site_header": "SpiceFit",
    "site_brand": "SpiceFit",
    "welcome_sign": "Welcome to SpiceFit Admin Panel",
    "copyright": "SpiceFit",
    "search_model": ["auth.User"],

    "topmenu_links": [
        {"name": "Home", "url": "/", "new_window": False},
        {"model": "auth.User"},
    ],

    # Theme
    "theme": "cerulean",

    # Custom app labels
    "custom_app_labels": {
        "base_app": "SpiceFit Core",
    },

    # Hide recent actions from dashboard
    "show_recent_actions": False,

    # Sidebar icons mapping
    "icons": {
        # Auth app
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",

        # SpiceFit Core models
        "base_app.ItemList": "fas fa-folder-open",           # 📂Menu → Categories
        "base_app.MenuRecipe": "fas fa-utensils",           # 📂MenuPage → Recipes
        "base_app.MoodList": "fas fa-theater-masks",        # 🎭Mood → Categories
        "base_app.MoodyRecipe": "fas fa-theater-masks",       # 🎭MoodyPage → Recipes
        "base_app.AboutUs": "fas fa-thumbtack",            # 📌About → AboutUs
        "base_app.mealChallenges": "fas fa-utensils",# 🍲MealPage → title
        "base_app.mealtitles": "fas fa-utensils",          # 🍲MealPage → Stitles
        "base_app.mealRecipe": "fas fa-utensils",          # 🍲MealPage → Recipes
        "base_app.QuickRecipe": "fas fa-bolt",             # ⚡QuickPage → Recipes
        "base_app.Profile": "fas fa-user-circle",          # 👤Users → Profiles
        "base_app.OwnRecipe": "fas fa-user-circle",          # 👨‍🍳Users → Recipes
        "base_app.book": "fas fa-book",                    # 📚BookPage → Books
        "base_app.Sitereview": "fas fa-star",             # ⭐Users Reviews
        "base_app.ParentTitle": "fas fa-puzzle-piece",    # 🧩ParentPage → Titles
        "base_app.ParentSubCatTitle": "fas fa-puzzle-piece", # 🧩ParentPage → Stitles
        "base_app.ParentRecipe": "fas fa-puzzle-piece",   # 🧩ParentPage → Recipes
        "base_app.Visitor": "fas fa-eye",                  # 👁️ Site Visitors
        "base_app.PlanCategory": "fas fa-leaf",           # 🥗 Plan Categories
        "base_app.Plan": "fas fa-leaf",               # 🥗Sub Plans
        "base_app.OurPlan": "fas fa-leaf",              # 🥗Plans recipes
        "base_app.Ingredient": "fas fa-lemon",            # 🥬 Ingredients
        "base_app.Recipe": "fas fa-lemon",           # 🥬 Ing. recipes
        "base_app.Cart": "fas fa-shopping-cart",          # 🛍️ Cart
        "base_app.CartItem": "fas fa-box",                # 🛍️ Cart Items
        "base_app.Order":"fas fa-box-open",               # 🛒 Orders
        "base_app.OrderItem": "fas fa-box-open",          # 🛒 Order Items
        "base_app.Payment": "fas fa-credit-card",         # 💳 Payments
        "base_app.Dashboard": "fas fa-chart-bar",         # 📊 report
        "base_app.Premium": "fas fa-crown",               # 👑 Premium Users
    }
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS':True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
]
WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3      ',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'spice',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}

# Timezone of your site
TIME_ZONE = 'Asia/Kolkata'  

# Let Django handle timezone-aware datetimes
USE_TZ = True